# Generated by Django 4.2.7 on 2023-11-20 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagehistory',
            name='user_email',
            field=models.CharField(max_length=255),
        ),
    ]
