# Generated by Django 4.2.7 on 2023-11-21 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_imagehistory_user_email'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='imagehistory',
            options={'verbose_name_plural': 'Image History'},
        ),
    ]
