# Generated by Django 4.2.7 on 2023-11-22 07:22

import app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_imagehistory_image_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagehistory',
            name='image_data',
            field=models.ImageField(upload_to=app.models.user_image_path),
        ),
    ]
