# Generated by Django 4.2.7 on 2023-12-01 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_imagehistory_image_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagehistory',
            name='detail',
            field=models.TextField(blank=True, null=True),
        ),
    ]
